Merge MuSig2 functions into ekrem/new-architecture
chainwayxyz/clementine pull request #206
Opened 2024-08-06 13:54 UTC by ozankaymak

# Description

Describe what this pull request does, here.

## Linked Issues

- Closes # (issue, if applicable)
- Related to # (issue)

## Testing

Describe how these changes were tested. If you've added new features, have you
added unit tests?

## Docs

Describe where this code is documented. If it changes a documented interface,
have the docs been updated?

2024-08-06 17:31 UTC, ekrembal reviewed
I think whats left is aggregate nonces and partial signatures. And tests also

2024-08-06 17:31 UTC, ekrembal commented on core/Cargo.toml
> +musig2 = { version = "0.0.11" }
we can use workspace=true here

2024-08-06 17:31 UTC, ekrembal commented on core/src/errors.rs
> +        BridgeError::KeyAggContextError
Pls propogate the original message in this

2024-08-06 17:31 UTC, ekrembal commented
We also need tweaked signatures as well

2024-08-07 12:10 UTC, ekrembal commented on core/src/musig2.rs
> +pub type MuSigAggNonce = [u8; 32];
This should be two curve points

2024-08-07 12:21 UTC, ekrembal commented on core/src/musig2.rs
> +    tweak: Option<[u8; 32]>,
we don't need tweak and pks here

2024-08-07 12:24 UTC, ekrembal commented
I think we need 3 tests:
- one for signing a 32 byte hash and verifying the agg signature with agg pubkey
- one for signing a taproot key spend that does have some script spending paths so tweak is needed
- one for signing a taproot from a script spending path with aggPubkey checkSig

2024-08-08 12:13 UTC, ekrembal commented on core/src/musig2.rs
> +
Let's add aggregate_signatures and aggregate_nonces here as well

2024-08-08 16:43 UTC, ekrembal requested changes

2024-08-08 16:43 UTC, ekrembal commented on core/src/transaction_builder.rs
> +        let taproot_builder = if n > 1 {
There is a code duplication here

2024-08-09 06:46 UTC, ozankaymak commented on core/src/transaction_builder.rs
> +        let taproot_builder = if n > 1 {
I do not understand what you mean.

2024-08-09 12:46 UTC, ekrembal approved these changes

2024-08-09 12:47 UTC, merged