Comments all over the place
chainwayxyz/clementine pull request #291
Opened 2024-09-10 12:16 UTC by ceyhunsen

# Description

This PR adds/improves comments to where users needs to change and users see.

## Linked Issues

- Related to #204

2024-09-10 14:37 UTC, ozankaymak requested changes

2024-09-10 14:37 UTC, ozankaymak commented on core/tests/data/test_config.toml
> +# User can take funds back after this amount of blocks.
Add "if the deposit fails"

2024-09-10 14:37 UTC, ozankaymak commented on core/tests/data/test_config.toml
>  operator_wallet_addresses = [
Maybe a comment for this as well?

2024-09-11 11:18 UTC, ceyhunsen commented on core/tests/data/test_config.toml
>  operator_wallet_addresses = [
Is this new comment makes sense?

2024-09-11 12:36 UTC, ozankaymak approved these changes

2024-09-11 12:37 UTC, merged